services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=jyotip
      - DB_PASSWORD=Jyoti@2002
      - DB_NAME=projectManagement 
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
  db:
    image: mysql:latest
    environment:
      MYSQL_USER: jyotip
      MYSQL_PASSWORD: Jyoti@2002
      MYSQL_DATABASE: projectManagement
      MYSQL_ROOT_PASSWORD: Jyoti@2002
    ports:
      - "3305:3306"
