# services:
#   server:
#     build: 
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"

#   client:
#     build: 
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     environment:
#       - HOST=0.0.0.0


services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/v1/api

  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=jyotip
      # - MYSQL_PASSWORD=Jyoti@2002
      - MYSQL_DB=projectManagement
      - MYSQL_DIALECT=mysql
      - JWT_SECRET=34kj34lhtjh34jlkth3kj4th32jhrjwlrnljnrkrje3rnj3krk
      - NODE_ENV=development

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_ROOT_PASSWORD=Jyoti@2002
      - MYSQL_DATABASE=projectManagement
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s

volumes:
  mysql_data:
